version: '3'
networks:
  elastic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
    networks:
      elastic-network:
        ipv4_address: 172.18.0.2
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      elastic-network:
        ipv4_address: 172.18.0.3
    ports:
      - "5500:5500"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    networks:
      elastic-network:
        ipv4_address: 172.18.0.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.14.1
    user: root
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      elastic-network:
        ipv4_address: 172.18.0.5


